package raf.rs.reservations.client.notificationservice.dto;

public enum NotificationCategory {

    EMAIL_VERIFICATION,
    RESET_PASSWORD,
    CLIENT_RESERVATION_CREATE,
    CLIENT_RESERVATION_CREATE_BENEFITS,
    RESERVATION_CONFIRM,
    RESERVATION_CONFIRM_BENEFITS,
    CLIENT_CANCELLATION,
    MANAGER_CANCELLATION,
    RESERVATION_REMINDER

}
